# Generated by Django 2.2.13 on 2021-06-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='subject',
        ),
    ]
