# Generated by Django 3.2.4 on 2021-07-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210702_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='Date',
            new_name='date',
        ),
    ]
